routes:
  /:
    template: home
  /about/team/: team
  /features/: features
  /work/: work
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account

collections:
  /blog/:
    permalink: /blog/{slug}/

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
